apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: online-boutique-cluster
  region: us-east-2
  version: "1.30"

managedNodeGroups:
  - name: boutique-workers
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
    volumeSize: 20
